<?php

declare(strict_types=1);

namespace Carl\Request;

use Override;
use Stringable;

/**
 * Adds a form-encoded payload (`application/x-www-form-urlencoded`) to the request.
 *
 * Sets `CURLOPT_POSTFIELDS` with a URL-encoded query string generated by {@see http_build_query}.
 * Combine with content-type decorators such as {@see WithContentType}.
 *
 * Note: Setting `CURLOPT_POSTFIELDS` can cause libcurl to use POST by default.
 * Ensure the origin defines the intended HTTP method (e.g., {@see PostRequest} or `CURLOPT_CUSTOMREQUEST`),
 * as this decorator does not enforce the verb.
 *
 * Decorates another {@see Request}.
 */
final readonly class WithFormBody implements Request
{
    /**
     * @param array<string, scalar|array<string, scalar>> $payload The data to encode as form data.
     *                       Nested arrays are encoded using PHP’s bracket notation (e.g., foo[bar]=baz).
     */
    public function __construct(
        private Request $origin,
        private array $payload,
    ) {
    }

    #[Override]
    public function options(): array
    {
        $options = $this->origin->options();
        $options[CURLOPT_POSTFIELDS] = http_build_query(
            $this->payload,
            '',
            '&',
            PHP_QUERY_RFC1738,
        );

        return $options;
    }
}
